apiVersion: v1
kind: Service
metadata:
  name: {{ include "piston.fullname" . }}-api
  labels:
    app: {{ include "piston.name" . }}
    component: api
  {{- if .Values.service.api.annotations }}
  annotations:
{{ toYaml .Values.service.api.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
  selector:
    app: {{ include "piston.name" . }}
    component: api
