apiVersion: v1
kind: Service
metadata:
  name: {{ include "piston.fullname" . }}-repo
  labels:
    app: {{ include "piston.name" . }}
    component: repo
  {{- if .Values.service.repo.annotations }}
  annotations:
{{ toYaml .Values.service.repo.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.repo.type }}
  ports:
    - port: {{ .Values.service.repo.port }}
      targetPort: {{ .Values.service.repo.targetPort }}
  selector:
    app: {{ include "piston.name" . }}
    component: repo
